### ISSUE TITLE
Can't set Locale for custom profile - it sets Timezone instead

### ISSUE THREAD

**Issue by donotdox** [z0ccc/Vytal#14]
If I set the profile to Custom I am able to set Timezone, Latitude, Longitude and User Agent. However, if I try to set the Locale I can type in the new locale. However, when I check:

a) The Locale has reverted back to whatever was in there previously
b) The Timezone is set to what I tried to set Locale to

An example: I set profile to New York
Timezone: America/New_York
Locale: en-US

I select Custom profile. I set locale to en-GB and close the tab.
I then check and see:
Timezone: en-GB
Locale: en-US

**Comment by z0ccc** [comment]
Will look into this. Tanks

**Comment by z0ccc** [comment]
This has been fixed and will be out in in next version.
