### ISSUE TITLE
Initial Load Timezone still detects home timezone

### ISSUE THREAD

**Issue by Tosoju** [z0ccc/Vytal#16]
Pretty self explanatory.

I'm using latest version of Brave. I install app. I load up https://vytal.io , Initial Load Intl.DateTimeFormat().resolvedOptions().timeZone still detects the home timezone. This affects all of the other time related detections on the site as well.

**Comment by Tosoju** [comment]
40 seconds after I posted this, I figured out the solution.

If on Brave Shields, Block Fingerprinting is enabled, then this issue happens. Allowing fingerprinting allows for the full spoof to work.

**Comment by Tosoju** [comment]
Disable Brave Shield Anti-fingerprinting

**Comment by Z3R013x** [comment]
Same happens in chrome where i do not have "Anti-Fingerprinting"

**Comment by z0ccc** [comment]
> Same happens in chrome where i do not have "Anti-Fingerprinting"

Does it happen only on the first load of a tab? There is a slight delay between when a new tab is opened and the debugger starts mocking the data. This allows for websites to get the original value of the data before it is changed. After the initial loading of a tab, this will no longer be an issue.

**Comment by Z3R013x** [comment]
> > Same happens in chrome where I do not have "Anti-Fingerprinting"
> 
> Does it happen only on the first load of a tab? There is a slight delay between when a new tab is opened and the debugger starts mocking the data. This allows for websites to get the original value of the data before it is changed. After the initial loading of a tab, this will no longer be an issue.

it only mocks my initial load after the refresh, no matter if I wait for a few seconds after turning on vytal or go to the website right after. vytal also doesn't have to be recently turned on to make this issue occur.

**Comment by z0ccc** [comment]
@Z3R013x Are you opening vytal in a new tab tho? Is it possible for you to record a video? Thanks

**Comment by Z3R013x** [comment]
no I'm turning on vytal while i'm on "new tab" page and then navigate to vytal.io

**Comment by z0ccc** [comment]
A new tab has to be initialized on an actually url, not a chrome page (like the default new tab page).
Looking for ways to improve this and possibly fix the whole initialization issue.

**Comment by Z3R013x** [comment]
Let me share video with you on mail. just to be clear.

**Comment by z0ccc** [comment]
ok sounds good
