### ISSUE TITLE
Extension has blocked access to all sites

### ISSUE THREAD

**Issue by Oxi-nya** [z0ccc/Vytal#17]
Although I'm not sure whether this is an issue or not, 
![image](https://user-images.githubusercontent.com/87499654/173806670-ca806e1e-60dc-42f0-9f31-36dfb52ac44a.png)

**Comment by z0ccc** [comment]
What do you mean it has 'blocked access to all sites'?

**Comment by Oxi-nya** [comment]
Maybe not blocked, but "This can read and change site data: On all sites" is grayed out and cannot be selected as it is a case for any other extension, and I'm not sure whether this should be happening

**Comment by z0ccc** [comment]
Vytal doesn't use the  permission's needed to "read and change site data: On all sites"
