### ISSUE TITLE
Notification of debugging the google chrome browser

### ISSUE THREAD

**Issue by Abwehr** [z0ccc/Vytal#18]
Hello. Please tell me how to disable constant notifications of debugging a browser in Google chrome. It appeared after the installation of your expansion, before with other extensions this was not.
![234](https://user-images.githubusercontent.com/107601818/173990810-01f4f4e4-71eb-4ead-8dd0-1ca237791242.png)

**Comment by Abwehr** [comment]
Found a solution

**Comment by z0ccc** [comment]
Hiding the bar can be done by using --silent-debugger-extension-api command-line switch.
