### ISSUE TITLE
The yellow strip covers top of the screen, does not go away.

### ISSUE THREAD

**Issue by Mantukai** [z0ccc/Vytal#19]
On opening every page the yellow strip covers top of the screen, does not go away.
Please add an option to either completely disable it or make it go away in 1-2 sec.  Otherwise I have to click cancel button on each page I open and closing the bar with a click does not always work instantaneously.

**Comment by z0ccc** [comment]
Yellow strip? Can you send me a screenshot? thanks

**Comment by donotdox** [comment]
On the default Chrome theme the debugging bar has a sort of yellow look (on my screen anyway). 

@Mantukai - if you are referring to the message "Vytal" started debugging this browser, this is answered in the readme:

Debugging bar
While the chrome.debugger API is active, a bar under the address bar is displayed. Hiding the bar is only possible when the --silent-debugger-extension-api command-line switch is used.

If you mean something else, I'm sorry for butting in
