### ISSUE TITLE
Location still detected

### ISSUE THREAD

**Issue by donotdox** [z0ccc/Vytal#22]
This isn't really an issue with Vytal, more wanting to understand the limitations.

As part of a cyber Capture the Flag (CTF) problem there is a webpage where you need to appear to be from Kazakhstan

The entry webpage is https://metaproblems.com/713bceb86c049123ed8a436c14d6b014/geo-lock/
When you click on "Online broadcasting" if you have successfully 'pretended' to be from Kazakhstan then you see a video snippet. Otherwise you see "This content is not available in your country"

I used a custom profile to appear to visit from Kazakhstan.

Timezone: Asia/Almaty
Locale: kk-KZ
Latitude: 43.277500
Longitude: 76.895833
User Agent: Left as default

I got the message "This content is not available in your country". I made sure the site permissions have Location set to allow.

I assume there are other settings I need to change in my browser or another extension or some combination.

**Comment by z0ccc** [comment]
Are you using a VPN aswell? Vytal does not change your ip address.

**Comment by donotdox** [comment]
Sorry, no. I should have realised that was the likely cause
